[workspace]
resolver = "3"
members = [
    "crates/blink",
    "crates/blink_algorithms",
    "crates/blink_core",
    "crates/blink_fermi_gbm",
    "crates/blink_hxmt_he",
    "crates/blink_lightning",
    "crates/blink_svom_grm",
    "crates/blink_task",
]
