[package]
name = "blink_search"
version = "0.1.0"
edition = "2024"

[dependencies]
blink_core = { version = "0.1.0", path = "../../core/blink_core" }
blink_workflow = { version = "0.1.0", path = "../blink_workflow" }
chrono = "0.4.42"
indicatif = "0.18.3"
nanoid = "0.4.0"
serde_json = "1.0.149"
