[package]
name = "blink_core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
fitsio = { version = "0.21.9", features = ["fitsio-src"] }
serde = "1.0.228"
thiserror = "2.0.17"
uom = { version = "0.37.0", features = ["serde"] }
