[package]
name = "blink-lightning"
version = "0.1.0"
edition = "2024"

[dependencies]
blink-core = { version = "0.1.0", path = "../blink-core" }
chrono = "0.4.42"
itertools = "0.14.0"
rusqlite = "0.37.0"
uom = "0.37.0"
